#
# Copyright 2017 The Abseil Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

load(
    "//absl/copts:configure_copts.bzl",
    "ABSL_DEFAULT_COPTS",
    "ABSL_DEFAULT_LINKOPTS",
    "ABSL_TEST_COPTS",
)

cxx_library(
    name = "atomic_hook",
    exported_headers = ["internal/atomic_hook.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
        ":core_headers",
    ],
)

cxx_library(
    name = "errno_saver",
    exported_headers = ["internal/errno_saver.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [":config"],
)

cxx_library(
    name = "log_severity",
    srcs = ["log_severity.cc"],
    visibility = ["PUBLIC"],
    exported_headers = ["log_severity.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":config",
        ":core_headers",
    ],
)

cxx_library(
    name = "raw_logging_internal",
    srcs = ["internal/raw_logging.cc"],
    exported_headers = ["internal/raw_logging.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":atomic_hook",
        ":config",
        ":core_headers",
        ":errno_saver",
        ":log_severity",
    ],
)

cxx_library(
    name = "spinlock_wait",
    srcs = [
        "internal/spinlock_wait.cc",
    ],
    headers = [
        "internal/spinlock_akaros.inc",
        "internal/spinlock_linux.inc",
        "internal/spinlock_posix.inc",
        "internal/spinlock_win32.inc",
    ],
    exported_headers = ["internal/spinlock_wait.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":base_internal",
        ":core_headers",
        ":errno_saver",
    ],
)

cxx_library(
    name = "config",
    visibility = ["PUBLIC"],
    exported_headers = [
        "config.h",
        "options.h",
        "policy_checks.h",
    ],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
)

cxx_library(
    name = "cycleclock_internal",
    exported_headers = [
        "internal/cycleclock_config.h",
        "internal/unscaledcycleclock_config.h",
    ],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":base_internal",
        ":config",
    ],
)

cxx_library(
    name = "dynamic_annotations",
    exported_headers = [
        "internal/dynamic_annotations.h",
        "dynamic_annotations.h",
    ],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = ["PUBLIC"],
    exported_deps = [
        ":config",
        ":core_headers",
    ],
)

cxx_library(
    name = "core_headers",
    visibility = ["PUBLIC"],
    exported_headers = [
        "internal/thread_annotations.h",
        "attributes.h",
        "const_init.h",
        "macros.h",
        "optimization.h",
        "port.h",
        "thread_annotations.h",
    ],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":config",
    ],
)

cxx_library(
    name = "malloc_internal",
    srcs = [
        "internal/low_level_alloc.cc",
    ],
    exported_headers = [
        "internal/direct_mmap.h",
        "internal/low_level_alloc.h",
    ],
    compiler_flags = ABSL_DEFAULT_COPTS,
    # + select({
    #     "//conditions:default": [],
    # }),
    linker_flags = ["-pthread"] + ABSL_DEFAULT_LINKOPTS,
    # TODO bwb
    # select({
    #        "//absl:msvc_compiler": [],
    #        "//absl:clang-cl_compiler": [],
    #        "//absl:wasm": [],
    #        "//conditions:default": ["-pthread"],
    #    })
    visibility = ["PUBLIC"],
    exported_deps = [
        ":base",
        ":base_internal",
        ":config",
        ":core_headers",
        ":dynamic_annotations",
        ":raw_logging_internal",
    ],
)

cxx_library(
    name = "base_internal",
    exported_headers = [
        "internal/hide_ptr.h",
        "internal/identity.h",
        "internal/inline_variable.h",
        "internal/invoke.h",
        "internal/scheduling_mode.h",
    ],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
        "//absl/meta:type_traits",
    ],
)

cxx_library(
    name = "base",
    srcs = [
        "internal/cycleclock.cc",
        "internal/spinlock.cc",
        "internal/sysinfo.cc",
        "internal/thread_identity.cc",
        "internal/unscaledcycleclock.cc",
    ],
    exported_headers = [
        "call_once.h",
        "casts.h",
        "internal/cycleclock.h",
        "internal/low_level_scheduling.h",
        "internal/per_thread_tls.h",
        "internal/spinlock.h",
        "internal/sysinfo.h",
        "internal/thread_identity.h",
        "internal/tsan_mutex_interface.h",
        "internal/unscaledcycleclock.h",
    ],
    visibility = ["PUBLIC"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    # TODO(bwb) investigate
    #linker_flags = select({
    #    "//absl:msvc_compiler": [
    #        "-DEFAULTLIB:advapi32.lib",
    #    ],
    #    "//absl:clang-cl_compiler": [
    #        "-DEFAULTLIB:advapi32.lib",
    #    ],
    #    "//absl:mingw_compiler": [
    #        "-DEFAULTLIB:advapi32.lib",
    #        "-ladvapi32",
    #    ],
    #    "//absl:wasm": [],
    #    "//conditions:default": ["-pthread"],
    #}) + ABSL_DEFAULT_LINKOPTS,
    linker_flags = ["-pthread"] + ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":atomic_hook",
        ":base_internal",
        ":config",
        ":core_headers",
        ":cycleclock_internal",
        ":dynamic_annotations",
        ":log_severity",
        ":raw_logging_internal",
        ":spinlock_wait",
        "//absl/meta:type_traits",
    ],
)

cxx_library(
    name = "atomic_hook_test_helper",
    srcs = ["internal/atomic_hook_test_helper.cc"],
    exported_headers = ["internal/atomic_hook_test_helper.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":atomic_hook",
        ":core_headers",
    ],
)

cxx_test(
    name = "atomic_hook_test",
    srcs = ["internal/atomic_hook_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":atomic_hook",
        ":atomic_hook_test_helper",
        ":core_headers",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "bit_cast_test",
    srcs = [
        "bit_cast_test.cc",
    ],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base",
        ":core_headers",
        "googletest//:gtest_main",
    ],
)

cxx_library(
    name = "throw_delegate",
    srcs = ["internal/throw_delegate.cc"],
    exported_headers = ["internal/throw_delegate.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
        ":raw_logging_internal",
    ],
)

cxx_test(
    name = "throw_delegate_test",
    srcs = ["throw_delegate_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":config",
        ":throw_delegate",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "errno_saver_test",
    srcs = ["internal/errno_saver_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":errno_saver",
        ":strerror",
        "googletest//:gtest_main",
    ],
)

cxx_library(
    name = "exception_testing",
    exported_headers = ["internal/exception_testing.h"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
        "googletest//:gtest",
    ],
)

cxx_library(
    name = "pretty_function",
    exported_headers = ["internal/pretty_function.h"],
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = ["//absl/..."],
)

cxx_library(
    name = "exception_safety_testing",
    srcs = ["internal/exception_safety_testing.cc"],
    exported_headers = ["internal/exception_safety_testing.h"],
    visibility = ["//absl/..."],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":config",
        ":pretty_function",
        "//absl/memory:memory",
        "//absl/meta:type_traits",
        "//absl/strings:strings",
        "//absl/utility:utility",
        "googletest//:gtest",
    ],
)

cxx_test(
    name = "exception_safety_testing_test",
    srcs = ["exception_safety_testing_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":exception_safety_testing",
        "//absl/memory:memory",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "inline_variable_test",
    srcs = [
        "inline_variable_test.cc",
        "inline_variable_test_a.cc",
        "inline_variable_test_b.cc",
    ],
    headers = [
        "internal/inline_variable_testing.h",
    ],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base_internal",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "invoke_test",
    srcs = ["invoke_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base_internal",
        "//absl/memory:memory",
        "//absl/strings:strings",
        "googletest//:gtest_main",
    ],
)

# Common test library made available for use in non-absl code that overrides
# AbslInternalSpinLockDelay and AbslInternalSpinLockWake.
cxx_library(
    name = "spinlock_test_common",
    srcs = ["spinlock_test_common.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":base",
        ":base_internal",
        ":config",
        ":core_headers",
        "//absl/synchronization:synchronization",
        "googletest//:gtest",
    ],
    # TODO(bwb) investigate
    # alwayslink = 1,
)

cxx_test(
    name = "spinlock_test",
    srcs = ["spinlock_test_common.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base",
        ":base_internal",
        ":config",
        ":core_headers",
        "//absl/synchronization:synchronization",
        "googletest//:gtest_main",
    ],
)

#cxx_library(
#    name = "spinlock_benchmark_common",
#    srcs = ["internal/spinlock_benchmark.cc"],
#    compiler_flags = ABSL_TEST_COPTS,
#    linker_flags = ABSL_DEFAULT_LINKOPTS,
#    deps = [
#        ":base",
#        ":base_internal",
#        ":raw_logging_internal",
#        "//absl/synchronization:synchronization",
#        "@com_github_google_benchmark//:benchmark_main",
#    ],
#    # TODO(bwb) investigate
#    # alwayslink = 1,
#)
#
#cxx_binary(
#    name = "spinlock_benchmark",
#    compiler_flags = ABSL_DEFAULT_COPTS,
#    linker_flags = ABSL_DEFAULT_LINKOPTS,
#    visibility = ["//visibility:private"],
#    exported_deps = [
#        ":spinlock_benchmark_common",
#    ],
#)

cxx_library(
    name = "endian",
    exported_headers = [
        "internal/endian.h",
        "internal/unaligned_access.h",
    ],
    visibility = ["PUBLIC"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":base",
        ":config",
        ":core_headers",
    ],
)

cxx_test(
    name = "endian_test",
    srcs = ["internal/endian_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    deps = [
        ":config",
        ":endian",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "config_test",
    srcs = ["config_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":config",
        "//absl/synchronization:thread_pool",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "call_once_test",
    srcs = ["call_once_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base",
        ":core_headers",
        "//absl/synchronization:synchronization",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "raw_logging_test",
    srcs = ["raw_logging_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":raw_logging_internal",
        "//absl/strings:strings",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "sysinfo_test",
    srcs = ["internal/sysinfo_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base",
        "//absl/synchronization:synchronization",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "low_level_alloc_test",
    srcs = ["internal/low_level_alloc_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":malloc_internal",
        "//absl/container:node_hash_map",
    ],
)

cxx_test(
    name = "thread_identity_test",
    srcs = ["internal/thread_identity_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":base",
        ":core_headers",
        "//absl/synchronization:synchronization",
        "googletest//:gtest_main",
    ],
)

#cxx_test(
#    name = "thread_identity_benchmark",
#    srcs = ["internal/thread_identity_benchmark.cc"],
#    compiler_flags = ABSL_TEST_COPTS,
#    linker_flags = ABSL_DEFAULT_LINKOPTS,
#    visibility = ["//visibility:private"],
#    deps = [
#        ":base",
#        "//absl/synchronization:synchronization",
#        "@com_github_google_benchmark//:benchmark_main",
#    ],
#)

cxx_library(
    name = "scoped_set_env",
    srcs = ["internal/scoped_set_env.cc"],
    exported_headers = ["internal/scoped_set_env.h"],
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
        ":raw_logging_internal",
    ],
)

cxx_test(
    name = "scoped_set_env_test",
    srcs = ["internal/scoped_set_env_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":scoped_set_env",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "log_severity_test",
    srcs = ["log_severity_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":log_severity",
        "//absl/flags:flag_internal",
        "//absl/flags:marshalling",
        "//absl/strings:strings",
        "googletest//:gtest_main",
    ],
)

cxx_library(
    name = "strerror",
    srcs = ["internal/strerror.cc"],
    exported_headers = ["internal/strerror.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
        ":core_headers",
        ":errno_saver",
    ],
)

cxx_test(
    name = "strerror_test",
    srcs = ["internal/strerror_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":strerror",
        "//absl/strings:strings",
        "googletest//:gtest_main",
    ],
)

#cxx_binary(
#    name = "strerror_benchmark",
#    srcs = ["internal/strerror_benchmark.cc"],
#    compiler_flags = ABSL_TEST_COPTS,
#    linker_flags = ABSL_DEFAULT_LINKOPTS,
#    visibility = ["//visibility:private"],
#    deps = [
#        ":strerror",
#        "@com_github_google_benchmark//:benchmark_main",
#    ],
#)

cxx_library(
    name = "fast_type_id",
    exported_headers = ["internal/fast_type_id.h"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    visibility = [
        "//absl/...",
    ],
    exported_deps = [
        ":config",
    ],
)

cxx_test(
    name = "fast_type_id_test",
    srcs = ["internal/fast_type_id_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":fast_type_id",
        "googletest//:gtest_main",
    ],
)

cxx_library(
    name = "prefetch",
    exported_headers = [
        "internal/prefetch.h",
        "prefetch.h",
    ],
    visibility = ["PUBLIC"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":config",
        ":core_headers",  # TODO(b/265984188): remove
    ],
)

cxx_test(
    name = "prefetch_test",
    srcs = [
        "internal/prefetch_test.cc",
        "prefetch_test.cc",
    ],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":prefetch",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "unique_small_name_test",
    srcs = ["internal/unique_small_name_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    #    linker_style = ["static"],
    deps = [
        ":core_headers",
        "//absl/strings:strings",
        "googletest//:gtest_main",
    ],
)

cxx_test(
    name = "optimization_test",
    srcs = ["optimization_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":core_headers",
        "//absl/types:optional",
        "googletest//:gtest_main",
    ],
)
