#
# Copyright 2017 The Abseil Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

load(
    "//absl/copts:configure_copts.bzl",
    "ABSL_DEFAULT_COPTS",
    "ABSL_DEFAULT_LINKOPTS",
    "ABSL_TEST_COPTS",
)

cxx_library(
    name = "algorithm",
    exported_headers = ["algorithm.h"],
    visibility = ["PUBLIC"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        "//absl/base:config",
    ],
)

cxx_test(
    name = "algorithm_test",
    srcs = ["algorithm_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":algorithm",
        "//absl/base:config",
        "googletest//:gtest_main",
    ],
)

cxx_binary(
    name = "algorithm_benchmark",
    srcs = ["equal_benchmark.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":algorithm",
        "//absl/base:core_headers",
    #    "@com_github_google_benchmark//:benchmark_main",
    ],
)

cxx_library(
    name = "container",
    exported_headers = [
        "container.h",
    ],
    visibility = ["PUBLIC"],
    compiler_flags = ABSL_DEFAULT_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    exported_deps = [
        ":algorithm",
        "//absl/base:core_headers",
        "//absl/meta:type_traits",
    ],
)

cxx_test(
    name = "container_test",
    srcs = ["container_test.cc"],
    compiler_flags = ABSL_TEST_COPTS,
    linker_flags = ABSL_DEFAULT_LINKOPTS,
    deps = [
        ":container",
        "//absl/base:base",
        "//absl/base:core_headers",
        "//absl/memory:memory",
        "//absl/types:span",
    #    "@com_google_googletest//:gtest_main",
    ],
)
